# Generated by Django 3.2 on 2021-04-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210410_1928'),
        ('orders', '0002_alter_orders_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.products'),
        ),
    ]
